### ISSUE TITLE
Incompatibility with testBox v2.7

### ISSUE THREAD

**Issue by Fridus** [seancoyne/testbox-runner#16]
Hi,

Keys name are not correct.

**Comment by seancoyne** [comment]
Can you provide any additional information? You've not provided much to go on

**Comment by daamsie** [comment]
I just ran into something like this.. I dare say it's the same issue. Basically, the node-runner is looking for uppercase key names, eg.. SPECSTATS but the output from the testrunner is camelCase - eg. specStats. 

This leads to a lot of ".. is undefined" type errors.

This seems likely to be a Lucee vs CF issue, since the JSON stringifier in CF often outputs keys in uppercase.

**Comment by seancoyne** [comment]
Perhaps we can convert the key names to upper case in the javascript code so it wont matter which engine or the if the setting is enabled to preserve key case is in use.

**Comment by daamsie** [comment]
That would probably be the most straightforward. Happy to have a create a PR for it if you like.

**Comment by seancoyne** [comment]
Yeah if you want to tackle it go for it!

**Comment by daamsie** [comment]
Done!

**Comment by seancoyne** [comment]
fixed in PR #20
